name: Initial project setup
description: Checkout the project and setup the system with brew, install java and android sdk, ruby and other dependencies

inputs:
  gitTag:
    description: 'Tag to check out'
    required: false

runs:
  using: "composite"
  steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.gitTag }}
    - name: Install brews
      shell: bash
      run: brew bundle
    - name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc

    # This does not work on Apple Silicon for now: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gmp.rb
    # - uses: ruby/setup-ruby@v1
    #   with:
    #     bundler-cache: true

    # Use workaround for now -->
    - name: Install ruby
      shell: bash
      run: rbenv install -s `cat .ruby-version`
    - name: Use rbenv shims
      shell: bash
      run: echo "~/.rbenv/shims" >> $GITHUB_PATH
    - name: Restore Dependencies
      uses: actions/cache/restore@v3
      id: cache-dependencies
      env:
        cache-name: cache-dependencies
      with:
        path: |
          vendor
          .bundle
        key: ${{ runner.os }}-${{ runner.name }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock') }}
    - name: Install dependencies
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      shell: bash
      run: bundle install
    - name: Save Dependencies
      uses: actions/cache/save@v3
      if: steps.cache-dependencies.outputs.cache-hit != 'true'
      env:
        cache-name: cache-dependencies
      with:
        path: |
          vendor
          .bundle
        key: ${{ runner.os }}-${{ runner.name }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock') }}
    # <-- Workaround
