name: Build a release version
description: Build and upload the app with a specific stage

inputs:
  stage:
    description: 'Stage to build'
    required: true
  gitTag:
    description: 'Tag to check out'
    required: false
  KEYSTORE_BASE64:
    description: 'Keystore in base64'
    required: true
  KEYSTORE_PASSWORD:
    description: 'Password for the key store'
    required: true
  FASTLANE_API_KEY:
    description: 'Fastlane API key'
    required: true
  UPLOAD_KEY_PASSWORD:
    description: 'Password for the upload key'
    required: true
  MATOMO_HOST:
    description: 'Matomo host'
    required: true
  MATOMO_SITE_ID:
    description: 'Matomo site ID'
    required: true
  SENTRY_PUBLIC_KEY:
    description: 'Sentry public key'
    required: true
  SENTRY_PROJECT_ID:
    description: 'Sentry project ID'
    required: true
  SENTRY_AUTH_TOKEN:
    description: 'Auth token for sentry.io'
    required: true
  SENTRY_PROJECT:
    description: 'sentry.io project'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup
      uses: ./.github/actions/setup
      with:
        gitTag: ${{ inputs.gitTag }}
    - name: Deploy key store
      shell: bash
      env:
        KEYSTORE_BASE64: ${{ inputs.KEYSTORE_BASE64 }}
      run: |
        KEYSTORE_PATH=$RUNNER_TEMP/keystore.jks
        echo -n "$KEYSTORE_BASE64" | base64 --decode -o $KEYSTORE_PATH
        echo "KEYSTORE_PATH=$KEYSTORE_PATH" >> $GITHUB_ENV
    - name: Deploy fastlane API key
      shell: bash
      env:
        FASTLANE_API_KEY: ${{ inputs.FASTLANE_API_KEY }}
      run: |
        FASTLANE_API_KEY_PATH=$RUNNER_TEMP/fastlane_api_key.json
        echo -n "$FASTLANE_API_KEY" > $FASTLANE_API_KEY_PATH
        echo "FASTLANE_API_KEY_PATH=$FASTLANE_API_KEY_PATH" >> $GITHUB_ENV
    - name: Build release and submit to specified platform (Google Play Store / GitHub)
      shell: bash
      env:
        KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
        KEYSTORE_PASSWORD: ${{ inputs.KEYSTORE_PASSWORD }}
        FASTLANE_API_KEY_PATH: ${{ env.FASTLANE_API_KEY_PATH }}
        UPLOAD_KEY_PASSWORD: ${{ inputs.UPLOAD_KEY_PASSWORD }}
        MATOMO_HOST: ${{ inputs.MATOMO_HOST }}
        MATOMO_SITE_ID: ${{ inputs.MATOMO_SITE_ID }}
        SENTRY_PUBLIC_KEY: ${{ inputs.SENTRY_PUBLIC_KEY }}
        SENTRY_PROJECT_ID: ${{ inputs.SENTRY_PROJECT_ID }}
        SENTRY_AUTH_TOKEN: ${{ inputs.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: digitalservice
        SENTRY_PROJECT: ${{ inputs.SENTRY_PROJECT }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        UNLEASH_API_KEY: ${{ inputs.UNLEASH_API_KEY }}
        UNLEASH_HOST: ${{ inputs.UNLEASH_HOST }}
      run: bundle exec fastlane release stage:${{ inputs.stage }}
