name: Submits dependencies to repository's dependency graph
on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Dependencies
    runs-on: [self-hosted, ARM64]
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@v0.8.4
        with:
          gradle-build-module: ":app"