name: Submits dependencies to repository's dependency graph
on:
  push:
    branches:
      - main

jobs:
  validate-gradle-wrapper:
    runs-on: [self-hosted, ARM64]
    steps:
      - uses: actions/checkout@v3
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b
  build:
    name: Dependencies
    runs-on: [self-hosted, ARM64]
    needs: [validate-gradle-wrapper]
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Gradle Dependency Submission
        uses: mikepenz/gradle-dependency-submission@aa82af7186ba17eb630a7d47c840ba8a3185ac91
        with:
          gradle-build-module: ":app"
