name: Checks on Pullrequests
on:
  pull_request

concurrency:
  group: ${{ github.head_ref || github.ref }} # Cancel old runs if they have not finished yet
  cancel-in-progress: true

# Necessary for ruby/setup-ruby which we can't use yet.
# env:
#   ImageOS: macos12

jobs:
  lint:
    runs-on: [self-hosted, ARM64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run Android linter and ktlint
        run: bundle exec fastlane lint
      - name: Upload lint report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: lint_report-${{ github.sha }}
          path: app/build/reports

  test:
    runs-on: [self-hosted, ARM64]
    needs: lint
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run test
        run: bundle exec fastlane test
      - name: Upload AndroidTest report
        uses: actions/upload-artifact@v3
        with:
          name: android_test_report-${{ github.sha }}
          path: |
            app/build/outputs/androidTest-results
            !app/build/outputs/androidTest-results/**/adb.additional*
