name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: false
      bumpBuildNumber:
        description: 'Bump build number'
        type: boolean
        required: true
        default: true

jobs:
  bumpVersion:
    runs-on: [self-hosted, ARM64]
    outputs:
      gitTag: ${{ steps.gitTag.outputs.gitTag }}
    steps:
      - name: Ensure on release branch
        run: |
          echo "Ensuring current branch $GITHUB_REF is 'release' branch…"
          [[ "$GITHUB_REF" == "refs/heads/release" ]]
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Update version name and bump version code
        env:
          VERSION: ${{ inputs.version }}
          BUMP_BUILD_NUMBER: ${{ inputs.bumpBuildNumber }}
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
        run: bundle exec fastlane bumpVersion
      - name: Export git tag
        id: gitTag
        env:
          VERSION: ${{ env.GIT_TAG }}
        run: echo "::set-output name=gitTag::${{ env.GIT_TAG }}"

  production:
    runs-on: [self-hosted, ARM64]
    needs: bumpVersion
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bumpVersion.outputs.gitTag }}
      - name: Build
        uses: ./.github/actions/release
        with:
          gitTag: ${{ needs.bumpVersion.outputs.gitTag }}
          stage: production
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          MATOMO_HOST: ${{ secrets.MATOMO_HOST_PRODUCTION }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID_PRODUCTION }}
          SENTRY_PUBLIC_KEY: ${{ secrets.SENTRY_PUBLIC_KEY_PRODUCTION }}
          SENTRY_PROJECT_ID: ${{ secrets.SENTRY_PROJECT_ID_PRODUCTION }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: useid-android
          UNLEASH_API_KEY: ${{ secrets.UNLEASH_API_KEY_PRODUCTION }}
          UNLEASH_HOST: ${{ secrets.UNLEASH_HOST }}

  preview:
    runs-on: [self-hosted, ARM64]
    needs: bumpVersion
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bumpVersion.outputs.gitTag }}
      - name: Build
        uses: ./.github/actions/release
        with:
          gitTag: ${{ needs.bumpVersion.outputs.gitTag }}
          stage: preview
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          MATOMO_HOST: ${{ secrets.MATOMO_HOST_PREVIEW }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID_PREVIEW }}
          SENTRY_PUBLIC_KEY: ${{ secrets.SENTRY_PUBLIC_KEY_PREVIEW }}
          SENTRY_PROJECT_ID: ${{ secrets.SENTRY_PROJECT_ID_PREVIEW }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: useid-preview-android
          UNLEASH_API_KEY: ${{ secrets.UNLEASH_API_KEY_PREVIEW }}
          UNLEASH_HOST: ${{ secrets.UNLEASH_HOST }}

  github:
    runs-on: [self-hosted, ARM64]
    needs: bumpVersion
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.bumpVersion.outputs.gitTag }}
      - name: Build
        uses: ./.github/actions/release
        with:
          gitTag: ${{ needs.bumpVersion.outputs.gitTag }}
          stage: github
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          MATOMO_HOST: ${{ secrets.MATOMO_HOST_PRODUCTION }}
          MATOMO_SITE_ID: ${{ secrets.MATOMO_SITE_ID_PRODUCTION }}
          SENTRY_PUBLIC_KEY: ${{ secrets.SENTRY_PUBLIC_KEY_PRODUCTION }}
          SENTRY_PROJECT_ID: ${{ secrets.SENTRY_PROJECT_ID_PRODUCTION }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_PROJECT: useid-android
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UNLEASH_API_KEY: ${{ secrets.UNLEASH_API_KEY_PRODUCTION }}
          UNLEASH_HOST: ${{ secrets.UNLEASH_HOST }}
