name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
        required: false
      bumpBuildNumber:
        description: 'Bump build number'
        type: boolean
        required: true
        default: true

jobs:
  bumpVersion:
    runs-on: self-hosted
    outputs:
      gitTag: ${{ steps.gitTag.outputs.gitTag }}
    steps:
      - name: Ensure on release branch
        run: |
          echo "Ensuring current branch $GITHUB_REF is 'release' branch…"
          [[ "$GITHUB_REF" == "refs/heads/release" ]]
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Update version name and bump version code
        env:
          VERSION: ${{ inputs.version }}
          BUMP_BUILD_NUMBER: ${{ inputs.bumpBuildNumber }}
          GITHUB_ENV: ${{ env.GITHUB_ENV }}
        run: bundle exec fastlane bumpVersion
      - name: Export git tag
        id: gitTag
        env:
          VERSION: ${{ env.GIT_TAG }}
        run: echo "::set-output name=gitTag::${{ env.GIT_TAG }}"

  production:
    runs-on: self-hosted
    needs: bumpVersion
    steps:
      - name: Build
        uses: ./.github/actions/release
        env:
          FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          FASTLANE_API_KEY_PATH: ${{ env.FASTLANE_API_KEY_PATH }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: digitalservice
          SENTRY_PROJECT: useid-android
        with:
          gitTag: ${{ needs.bumpVersion.outputs.gitTag }}
          stage: production

  preview:
    runs-on: self-hosted
    needs: bumpVersion
    steps:
      - name: Build
        uses: ./.github/actions/release
        env:
          FASTLANE_API_KEY: ${{ secrets.FASTLANE_API_KEY }}
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          FASTLANE_API_KEY_PATH: ${{ env.FASTLANE_API_KEY_PATH }}
          UPLOAD_KEY_PASSWORD: ${{ secrets.UPLOAD_KEY_PASSWORD }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: digitalservice
          SENTRY_PROJECT: useid-preview-android
        with:
          gitTag: ${{ needs.bumpVersion.outputs.gitTag }}
          stage: preview